services:
  app:
    build: .
    container_name: my-spring-app
    env_file: .env
    environment:
      SERVER_FORWARD_HEADERS_STRATEGY: native
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "trap 'exit' TERM INT; sleep infinity & wait" ]